const countries = {
  "aruba": "aw",
  "afghanistan": "af",
  "angola": "ao",
  "anguilla": "ai",
  "åland islands": "ax",
  "albania": "al",
  "andorra": "ad",
  "united arab emirates": "ae",
  "argentina": "ar",
  "armenia": "am",
  "american samoa": "as",
  "antarctica": "aq",
  "french southern territories": "tf",
  "antigua and barbuda": "ag",
  "australia": "au",
  "austria": "at",
  "azerbaijan": "az",
  "burundi": "bi",
  "belgium": "be",
  "benin": "bj",
  "bonaire, sint eustatius and saba": "bq",
  "burkina faso": "bf",
  "bangladesh": "bd",
  "bulgaria": "bg",
  "bahrain": "bh",
  "bahamas": "bs",
  "bosnia and herzegovina": "ba",
  "saint barthélemy": "bl",
  "belarus": "by",
  "belize": "bz",
  "bermuda": "bm",
  "bolivia, plurinational state of": "bo",
  "brazil": "br",
  "barbados": "bb",
  "brunei darussalam": "bn",
  "bhutan": "bt",
  "bouvet island": "bv",
  "botswana": "bw",
  "central african republic": "cf",
  "canada": "ca",
  "cocos (keeling) islands": "cc",
  "switzerland": "ch",
  "chile": "cl",
  "china": "cn",
  "côte d'ivoire": "ci",
  "cameroon": "cm",
  "congo, the democratic republic of the": "cd",
  "congo": "cg",
  "cook islands": "ck",
  "colombia": "co",
  "comoros": "km",
  "cabo verde": "cv",
  "costa rica": "cr",
  "cuba": "cu",
  "curaçao": "cw",
  "christmas island": "cx",
  "cayman islands": "ky",
  "cyprus": "cy",
  "czechia": "cz",
  "germany": "de",
  "djibouti": "dj",
  "dominica": "dm",
  "denmark": "dk",
  "dominican republic": "do",
  "algeria": "dz",
  "ecuador": "ec",
  "egypt": "eg",
  "eritrea": "er",
  "western sahara": "eh",
  "spain": "es",
  "estonia": "ee",
  "ethiopia": "et",
  "finland": "fi",
  "fiji": "fj",
  "falkland islands (malvinas)": "fk",
  "france": "fr",
  "faroe islands": "fo",
  "micronesia, federated states of": "fm",
  "gabon": "ga",
  "united kingdom": "gb",
  "georgia": "ge",
  "guernsey": "gg",
  "ghana": "gh",
  "gibraltar": "gi",
  "guinea": "gn",
  "guadeloupe": "gp",
  "gambia": "gm",
  "guinea-bissau": "gw",
  "equatorial guinea": "gq",
  "greece": "gr",
  "grenada": "gd",
  "greenland": "gl",
  "guatemala": "gt",
  "french guiana": "gf",
  "guam": "gu",
  "guyana": "gy",
  "hong kong": "hk",
  "heard island and mcdonald islands": "hm",
  "honduras": "hn",
  "croatia": "hr",
  "haiti": "ht",
  "hungary": "hu",
  "indonesia": "id",
  "isle of man": "im",
  "india": "in",
  "british indian ocean territory": "io",
  "ireland": "ie",
  "iran, islamic republic of": "ir",
  "iraq": "iq",
  "iceland": "is",
  "israel": "il",
  "italy": "it",
  "jamaica": "jm",
  "jersey": "je",
  "jordan": "jo",
  "japan": "jp",
  "kazakhstan": "kz",
  "kenya": "ke",
  "kyrgyzstan": "kg",
  "cambodia": "kh",
  "kiribati": "ki",
  "saint kitts and nevis": "kn",
  "korea, republic of": "kr",
  "kuwait": "kw",
  "lao people's democratic republic": "la",
  "lebanon": "lb",
  "liberia": "lr",
  "libya": "ly",
  "saint lucia": "lc",
  "liechtenstein": "li",
  "sri lanka": "lk",
  "lesotho": "ls",
  "lithuania": "lt",
  "luxembourg": "lu",
  "latvia": "lv",
  "macao": "mo",
  "saint martin (french part)": "mf",
  "morocco": "ma",
  "monaco": "mc",
  "moldova, republic of": "md",
  "madagascar": "mg",
  "maldives": "mv",
  "mexico": "mx",
  "marshall islands": "mh",
  "north macedonia": "mk",
  "mali": "ml",
  "malta": "mt",
  "myanmar": "mm",
  "montenegro": "me",
  "mongolia": "mn",
  "northern mariana islands": "mp",
  "mozambique": "mz",
  "mauritania": "mr",
  "montserrat": "ms",
  "martinique": "mq",
  "mauritius": "mu",
  "malawi": "mw",
  "malaysia": "my",
  "mayotte": "yt",
  "namibia": "na",
  "new caledonia": "nc",
  "niger": "ne",
  "norfolk island": "nf",
  "nigeria": "ng",
  "nicaragua": "ni",
  "niue": "nu",
  "netherlands": "nl",
  "norway": "no",
  "nepal": "np",
  "nauru": "nr",
  "new zealand": "nz",
  "oman": "om",
  "pakistan": "pk",
  "panama": "pa",
  "pitcairn": "pn",
  "peru": "pe",
  "philippines": "ph",
  "palau": "pw",
  "papua new guinea": "pg",
  "poland": "pl",
  "puerto rico": "pr",
  "korea, democratic people's republic of": "kp",
  "portugal": "pt",
  "paraguay": "py",
  "palestine, state of": "ps",
  "french polynesia": "pf",
  "qatar": "qa",
  "réunion": "re",
  "romania": "ro",
  "russian federation": "ru",
  "rwanda": "rw",
  "saudi arabia": "sa",
  "sudan": "sd",
  "senegal": "sn",
  "singapore": "sg",
  "south georgia and the south sandwich islands": "gs",
  "saint helena, ascension and tristan da cunha": "sh",
  "svalbard and jan mayen": "sj",
  "solomon islands": "sb",
  "sierra leone": "sl",
  "el salvador": "sv",
  "san marino": "sm",
  "somalia": "so",
  "saint pierre and miquelon": "pm",
  "serbia": "rs",
  "south sudan": "ss",
  "sao tome and principe": "st",
  "suriname": "sr",
  "slovakia": "sk",
  "slovenia": "si",
  "sweden": "se",
  "eswatini": "sz",
  "sint maarten (dutch part)": "sx",
  "seychelles": "sc",
  "syrian arab republic": "sy",
  "turks and caicos islands": "tc",
  "chad": "td",
  "togo": "tg",
  "thailand": "th",
  "tajikistan": "tj",
  "tokelau": "tk",
  "turkmenistan": "tm",
  "timor-leste": "tl",
  "tonga": "to",
  "trinidad and tobago": "tt",
  "tunisia": "tn",
  "turkey": "tr",
  "tuvalu": "tv",
  "taiwan, province of china": "tw",
  "tanzania, united republic of": "tz",
  "uganda": "ug",
  "ukraine": "ua",
  "united states minor outlying islands": "um",
  "uruguay": "uy",
  "united states": "us",
  "uzbekistan": "uz",
  "holy see (vatican city state)": "va",
  "saint vincent and the grenadines": "vc",
  "venezuela, bolivarian republic of": "ve",
  "virgin islands, british": "vg",
  "virgin islands, u.s.": "vi",
  "viet nam": "vn",
  "vanuatu": "vu",
  "wallis and futuna": "wf",
  "samoa": "ws",
  "yemen": "ye",
  "south africa": "za",
  "zambia": "zm",
  "zimbabwe": "zw"
}

const reversedCountries = Object.fromEntries(
  Object.entries(countries).map(([key, value]) => [value, key])
);

module.exports = {
  countries,
  reversedCountries,
  getCountryCode: (countryName) => {
    const normalized = countryName.toLowerCase();
    return countries[normalized] || null;
  },
  getCountryName: (countryCode) => {
    return reversedCountries[countryCode.toLowerCase()] || null;
  }
};